# Generated by Django 5.0.1 on 2024-01-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efp_app', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quatity', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efp_app.category')),
                ('farmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efp_app.farmer')),
            ],
        ),
    ]
