# Generated by Django 5.0.1 on 2024-01-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efp_app', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
